/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LeadStatus = IDL.Variant({
  'won' : IDL.Null,
  'cold' : IDL.Null,
  'lost' : IDL.Null,
  'proposalSent' : IDL.Null,
  'contacted' : IDL.Null,
  'interested' : IDL.Null,
  'qualified' : IDL.Null,
});
export const OutreachActivity = IDL.Record({
  'createdAt' : IDL.Int,
  'sent' : IDL.Bool,
  'platform' : IDL.Text,
  'leadId' : IDL.Text,
  'message' : IDL.Text,
  'replied' : IDL.Bool,
  'followUpDate' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Project = IDL.Record({
  'id' : IDL.Text,
  'files' : IDL.Vec(ExternalBlob),
  'completion' : IDL.Nat,
  'status' : IDL.Text,
  'clientId' : IDL.Text,
  'agency' : IDL.Text,
  'notes' : IDL.Text,
  'serviceId' : IDL.Text,
  'startDate' : IDL.Int,
  'milestones' : IDL.Vec(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'revenue' : IDL.Nat,
  'name' : IDL.Text,
  'agency' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'salesCount' : IDL.Nat,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : LeadStatus,
  'contact' : IDL.Text,
  'owner' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'revenuePotential' : IDL.Nat,
  'agency' : IDL.Text,
  'niche' : IDL.Text,
});
export const DealStatus = IDL.Variant({
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'open' : IDL.Null,
  'proposalSent' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Text,
  'status' : DealStatus,
  'closeDate' : IDL.Opt(IDL.Int),
  'value' : IDL.Nat,
  'createdAt' : IDL.Int,
  'agency' : IDL.Text,
  'leadId' : IDL.Text,
});
export const ClientServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Text,
  'createdAt' : IDL.Int,
  'agency' : IDL.Text,
  'details' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'revenueGoal' : IDL.Nat,
  'principal' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'subscriptionPlan' : IDL.Text,
  'agency' : IDL.Text,
  'mobileNumber' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLead' : IDL.Func(
      [
        IDL.Record({
          'id' : IDL.Text,
          'status' : LeadStatus,
          'contact' : IDL.Text,
          'owner' : IDL.Text,
          'city' : IDL.Text,
          'name' : IDL.Text,
          'revenuePotential' : IDL.Nat,
          'agency' : IDL.Text,
          'niche' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'addOutreach' : IDL.Func([OutreachActivity], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'addService' : IDL.Func([Service], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeProject' : IDL.Func([IDL.Text], [], []),
  'createClientServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAgencyAnalytics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(Lead),
        IDL.Vec(Deal),
        IDL.Vec(OutreachActivity),
        IDL.Vec(Service),
        IDL.Vec(Project),
      ],
      ['query'],
    ),
  'getAllClientServiceRequests' : IDL.Func(
      [],
      [IDL.Vec(ClientServiceRequest)],
      ['query'],
    ),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllOutreachActivities' : IDL.Func(
      [],
      [IDL.Vec(OutreachActivity)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientServiceRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ClientServiceRequest)],
      ['query'],
    ),
  'getClientServiceRequestsByAgency' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClientServiceRequest)],
      ['query'],
    ),
  'getUserDeals' : IDL.Func([IDL.Text], [IDL.Vec(Deal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importLeads' : IDL.Func([IDL.Vec(Lead), IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        UserRole,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDealStatus' : IDL.Func([IDL.Text, DealStatus], [], []),
  'updateLeadStatus' : IDL.Func([IDL.Text, LeadStatus], [], []),
  'updateServiceStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LeadStatus = IDL.Variant({
    'won' : IDL.Null,
    'cold' : IDL.Null,
    'lost' : IDL.Null,
    'proposalSent' : IDL.Null,
    'contacted' : IDL.Null,
    'interested' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const OutreachActivity = IDL.Record({
    'createdAt' : IDL.Int,
    'sent' : IDL.Bool,
    'platform' : IDL.Text,
    'leadId' : IDL.Text,
    'message' : IDL.Text,
    'replied' : IDL.Bool,
    'followUpDate' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Project = IDL.Record({
    'id' : IDL.Text,
    'files' : IDL.Vec(ExternalBlob),
    'completion' : IDL.Nat,
    'status' : IDL.Text,
    'clientId' : IDL.Text,
    'agency' : IDL.Text,
    'notes' : IDL.Text,
    'serviceId' : IDL.Text,
    'startDate' : IDL.Int,
    'milestones' : IDL.Vec(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'revenue' : IDL.Nat,
    'name' : IDL.Text,
    'agency' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'salesCount' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : LeadStatus,
    'contact' : IDL.Text,
    'owner' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'revenuePotential' : IDL.Nat,
    'agency' : IDL.Text,
    'niche' : IDL.Text,
  });
  const DealStatus = IDL.Variant({
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'open' : IDL.Null,
    'proposalSent' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Text,
    'status' : DealStatus,
    'closeDate' : IDL.Opt(IDL.Int),
    'value' : IDL.Nat,
    'createdAt' : IDL.Int,
    'agency' : IDL.Text,
    'leadId' : IDL.Text,
  });
  const ClientServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Text,
    'createdAt' : IDL.Int,
    'agency' : IDL.Text,
    'details' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'revenueGoal' : IDL.Nat,
    'principal' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'subscriptionPlan' : IDL.Text,
    'agency' : IDL.Text,
    'mobileNumber' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLead' : IDL.Func(
        [
          IDL.Record({
            'id' : IDL.Text,
            'status' : LeadStatus,
            'contact' : IDL.Text,
            'owner' : IDL.Text,
            'city' : IDL.Text,
            'name' : IDL.Text,
            'revenuePotential' : IDL.Nat,
            'agency' : IDL.Text,
            'niche' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'addOutreach' : IDL.Func([OutreachActivity], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'addService' : IDL.Func([Service], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeProject' : IDL.Func([IDL.Text], [], []),
    'createClientServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAgencyAnalytics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(Lead),
          IDL.Vec(Deal),
          IDL.Vec(OutreachActivity),
          IDL.Vec(Service),
          IDL.Vec(Project),
        ],
        ['query'],
      ),
    'getAllClientServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ClientServiceRequest)],
        ['query'],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllOutreachActivities' : IDL.Func(
        [],
        [IDL.Vec(OutreachActivity)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientServiceRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ClientServiceRequest)],
        ['query'],
      ),
    'getClientServiceRequestsByAgency' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClientServiceRequest)],
        ['query'],
      ),
    'getUserDeals' : IDL.Func([IDL.Text], [IDL.Vec(Deal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importLeads' : IDL.Func([IDL.Vec(Lead), IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          UserRole,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDealStatus' : IDL.Func([IDL.Text, DealStatus], [], []),
    'updateLeadStatus' : IDL.Func([IDL.Text, LeadStatus], [], []),
    'updateServiceStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };