/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Text,
  'createdAt' : IDL.Int,
  'agency' : IDL.Text,
  'details' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'contact' : IDL.Text,
  'owner' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'revenuePotential' : IDL.Nat,
  'agency' : IDL.Text,
  'niche' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'stripe' : IDL.Null,
  'razorpay' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Project = IDL.Record({
  'id' : IDL.Text,
  'files' : IDL.Vec(ExternalBlob),
  'completion' : IDL.Nat,
  'status' : IDL.Text,
  'clientId' : IDL.Text,
  'agency' : IDL.Text,
  'notes' : IDL.Text,
  'serviceId' : IDL.Text,
  'startDate' : IDL.Int,
  'milestones' : IDL.Vec(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : IDL.Text,
  'active' : IDL.Bool,
  'revenue' : IDL.Nat,
  'cost' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'agency' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'shortDescription' : IDL.Text,
  'serviceSubType' : IDL.Text,
  'niche' : IDL.Text,
  'deliverables' : IDL.Vec(IDL.Text),
  'salesCount' : IDL.Nat,
  'detailedDescription' : IDL.Text,
  'price' : IDL.Nat,
  'requirements' : IDL.Vec(IDL.Text),
  'supportedProviders' : IDL.Vec(IDL.Text),
});
export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'serviceId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'revenueGoal' : IDL.Nat,
  'principal' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'subscriptionPlan' : IDL.Text,
  'agency' : IDL.Text,
  'mobileNumber' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'totalRevenue' : IDL.Nat,
});
export const PaymentSettings = IDL.Record({
  'upiDetails' : IDL.Text,
  'razorpayLink' : IDL.Text,
  'stripeLink' : IDL.Text,
});
export const Settings = IDL.Record({
  'defaultSort' : IDL.Text,
  'pricingType' : IDL.Text,
  'defaultValues' : IDL.Text,
  'onboardingCompleted' : IDL.Bool,
  'tutorialStage' : IDL.Int,
  'timeZone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClientServiceRequest' : IDL.Func([ClientServiceRequest], [], []),
  'createLead' : IDL.Func([Lead], [], []),
  'createPayment' : IDL.Func(
      [IDL.Text, IDL.Nat, PaymentMethod],
      [IDL.Text],
      [],
    ),
  'createProject' : IDL.Func([Project], [], []),
  'createService' : IDL.Func([Service], [], []),
  'deleteLead' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientServiceRequests' : IDL.Func(
      [],
      [IDL.Vec(ClientServiceRequest)],
      ['query'],
    ),
  'getLeadsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Lead)],
      ['query'],
    ),
  'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLead' : IDL.Func([IDL.Text, Lead], [], []),
  'updatePaymentSettings' : IDL.Func([PaymentSettings], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  'updateProject' : IDL.Func([IDL.Text, Project], [], []),
  'updateService' : IDL.Func([IDL.Text, Service], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Text,
    'createdAt' : IDL.Int,
    'agency' : IDL.Text,
    'details' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'contact' : IDL.Text,
    'owner' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'revenuePotential' : IDL.Nat,
    'agency' : IDL.Text,
    'niche' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'stripe' : IDL.Null,
    'razorpay' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Project = IDL.Record({
    'id' : IDL.Text,
    'files' : IDL.Vec(ExternalBlob),
    'completion' : IDL.Nat,
    'status' : IDL.Text,
    'clientId' : IDL.Text,
    'agency' : IDL.Text,
    'notes' : IDL.Text,
    'serviceId' : IDL.Text,
    'startDate' : IDL.Int,
    'milestones' : IDL.Vec(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : IDL.Text,
    'active' : IDL.Bool,
    'revenue' : IDL.Nat,
    'cost' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'agency' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'shortDescription' : IDL.Text,
    'serviceSubType' : IDL.Text,
    'niche' : IDL.Text,
    'deliverables' : IDL.Vec(IDL.Text),
    'salesCount' : IDL.Nat,
    'detailedDescription' : IDL.Text,
    'price' : IDL.Nat,
    'requirements' : IDL.Vec(IDL.Text),
    'supportedProviders' : IDL.Vec(IDL.Text),
  });
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'serviceId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'revenueGoal' : IDL.Nat,
    'principal' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'subscriptionPlan' : IDL.Text,
    'agency' : IDL.Text,
    'mobileNumber' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'totalRevenue' : IDL.Nat,
  });
  const PaymentSettings = IDL.Record({
    'upiDetails' : IDL.Text,
    'razorpayLink' : IDL.Text,
    'stripeLink' : IDL.Text,
  });
  const Settings = IDL.Record({
    'defaultSort' : IDL.Text,
    'pricingType' : IDL.Text,
    'defaultValues' : IDL.Text,
    'onboardingCompleted' : IDL.Bool,
    'tutorialStage' : IDL.Int,
    'timeZone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClientServiceRequest' : IDL.Func([ClientServiceRequest], [], []),
    'createLead' : IDL.Func([Lead], [], []),
    'createPayment' : IDL.Func(
        [IDL.Text, IDL.Nat, PaymentMethod],
        [IDL.Text],
        [],
      ),
    'createProject' : IDL.Func([Project], [], []),
    'createService' : IDL.Func([Service], [], []),
    'deleteLead' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ClientServiceRequest)],
        ['query'],
      ),
    'getLeadsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Lead)],
        ['query'],
      ),
    'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLead' : IDL.Func([IDL.Text, Lead], [], []),
    'updatePaymentSettings' : IDL.Func([PaymentSettings], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
    'updateProject' : IDL.Func([IDL.Text, Project], [], []),
    'updateService' : IDL.Func([IDL.Text, Service], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };