/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientServiceRequest {
  'id' : string,
  'principal' : string,
  'createdAt' : bigint,
  'agency' : string,
  'details' : [] | [string],
  'serviceId' : string,
}
export interface Deal {
  'id' : string,
  'status' : string,
  'closeDate' : [] | [bigint],
  'value' : bigint,
  'createdAt' : bigint,
  'agency' : string,
  'leadId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Lead {
  'id' : string,
  'status' : string,
  'contact' : string,
  'owner' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'revenuePotential' : bigint,
  'agency' : string,
  'niche' : string,
}
export interface OutreachActivity {
  'createdAt' : bigint,
  'sent' : boolean,
  'platform' : string,
  'leadId' : string,
  'message' : string,
  'replied' : boolean,
  'followUpDate' : bigint,
}
export interface Project {
  'id' : string,
  'files' : Array<ExternalBlob>,
  'completion' : bigint,
  'status' : string,
  'clientId' : string,
  'agency' : string,
  'notes' : string,
  'serviceId' : string,
  'startDate' : bigint,
  'milestones' : Array<string>,
}
export interface Service {
  'id' : string,
  'serviceType' : string,
  'active' : boolean,
  'revenue' : bigint,
  'cost' : bigint,
  'date' : string,
  'name' : string,
  'time' : string,
  'agency' : string,
  'deliveryTime' : string,
  'serviceSubType' : string,
  'niche' : string,
  'salesCount' : bigint,
  'price' : bigint,
}
export interface Settings {
  'defaultSort' : string,
  'pricingType' : string,
  'defaultValues' : string,
  'onboardingCompleted' : boolean,
  'tutorialStage' : bigint,
  'timeZone' : string,
}
export interface UserProfile {
  'revenueGoal' : bigint,
  'principal' : string,
  'name' : string,
  'role' : string,
  'subscriptionPlan' : string,
  'agency' : string,
  'mobileNumber' : [] | [string],
  'email' : string,
  'totalRevenue' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLead' : ActorMethod<
    [
      {
        'id' : string,
        'status' : string,
        'contact' : string,
        'owner' : string,
        'city' : string,
        'name' : string,
        'revenuePotential' : bigint,
        'agency' : string,
        'niche' : string,
      },
    ],
    undefined
  >,
  'addOutreach' : ActorMethod<[OutreachActivity], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeProject' : ActorMethod<[string], undefined>,
  'createClientServiceRequest' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
  'getAgencyAnalytics' : ActorMethod<
    [string],
    [
      Array<Lead>,
      Array<Deal>,
      Array<OutreachActivity>,
      Array<Service>,
      Array<Project>,
    ]
  >,
  'getAllClientServiceRequests' : ActorMethod<[], Array<ClientServiceRequest>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllOutreachActivities' : ActorMethod<[], Array<OutreachActivity>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientServiceRequest' : ActorMethod<
    [string],
    [] | [ClientServiceRequest]
  >,
  'getClientServiceRequestsByAgency' : ActorMethod<
    [string],
    Array<ClientServiceRequest>
  >,
  'getDealsForExport' : ActorMethod<[], Array<Deal>>,
  'getLeadsForExport' : ActorMethod<[], Array<Lead>>,
  'getOutreachActivitiesForExport' : ActorMethod<[], Array<OutreachActivity>>,
  'getProjectsForExport' : ActorMethod<[], Array<Project>>,
  'getServiceById' : ActorMethod<[string], [] | [Service]>,
  'getServicesForExport' : ActorMethod<[], Array<Service>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserDeals' : ActorMethod<[string], Array<Deal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importLeads' : ActorMethod<[Array<Lead>, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, [] | [string], string, string, bigint, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDealStatus' : ActorMethod<[string, string], undefined>,
  'updateLeadStatus' : ActorMethod<[string, string], undefined>,
  'updateServiceStatus' : ActorMethod<[string, boolean], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];