/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientServiceRequest {
  'id' : string,
  'principal' : string,
  'createdAt' : bigint,
  'agency' : string,
  'details' : [] | [string],
  'serviceId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Lead {
  'id' : string,
  'status' : string,
  'contact' : string,
  'owner' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'revenuePotential' : bigint,
  'agency' : string,
  'niche' : string,
}
export interface Payment {
  'id' : string,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'serviceId' : string,
  'amount' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'stripe' : null } |
  { 'razorpay' : null };
export interface PaymentSettings {
  'upiDetails' : string,
  'razorpayLink' : string,
  'stripeLink' : string,
}
export type PaymentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface Project {
  'id' : string,
  'files' : Array<ExternalBlob>,
  'completion' : bigint,
  'status' : string,
  'clientId' : string,
  'agency' : string,
  'notes' : string,
  'serviceId' : string,
  'startDate' : bigint,
  'milestones' : Array<string>,
}
export interface Service {
  'id' : string,
  'serviceType' : string,
  'active' : boolean,
  'revenue' : bigint,
  'cost' : bigint,
  'date' : string,
  'name' : string,
  'time' : string,
  'agency' : string,
  'deliveryTime' : string,
  'shortDescription' : string,
  'serviceSubType' : string,
  'niche' : string,
  'deliverables' : Array<string>,
  'salesCount' : bigint,
  'detailedDescription' : string,
  'price' : bigint,
  'requirements' : Array<string>,
  'supportedProviders' : Array<string>,
}
export interface Settings {
  'defaultSort' : string,
  'pricingType' : string,
  'defaultValues' : string,
  'onboardingCompleted' : boolean,
  'tutorialStage' : bigint,
  'timeZone' : string,
}
export interface UserProfile {
  'revenueGoal' : bigint,
  'principal' : string,
  'name' : string,
  'role' : string,
  'subscriptionPlan' : string,
  'agency' : string,
  'mobileNumber' : [] | [string],
  'email' : string,
  'totalRevenue' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClientServiceRequest' : ActorMethod<[ClientServiceRequest], undefined>,
  'createLead' : ActorMethod<[Lead], undefined>,
  'createPayment' : ActorMethod<[string, bigint, PaymentMethod], string>,
  'createProject' : ActorMethod<[Project], undefined>,
  'createService' : ActorMethod<[Service], undefined>,
  'deleteLead' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientServiceRequests' : ActorMethod<[], Array<ClientServiceRequest>>,
  'getLeadsPaginated' : ActorMethod<[bigint, bigint], Array<Lead>>,
  'getPayment' : ActorMethod<[string], [] | [Payment]>,
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getService' : ActorMethod<[string], [] | [Service]>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserPayments' : ActorMethod<[], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLead' : ActorMethod<[string, Lead], undefined>,
  'updatePaymentSettings' : ActorMethod<[PaymentSettings], undefined>,
  'updatePaymentStatus' : ActorMethod<[string, PaymentStatus], undefined>,
  'updateProject' : ActorMethod<[string, Project], undefined>,
  'updateService' : ActorMethod<[string, Service], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];