/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ClientServiceRequest {
    id: string;
    principal: string;
    createdAt: bigint;
    agency: string;
    details?: string;
    serviceId: string;
}
export interface OutreachActivity {
    createdAt: bigint;
    sent: boolean;
    platform: string;
    leadId: string;
    message: string;
    replied: boolean;
    followUpDate: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: string;
    active: boolean;
    revenue: bigint;
    name: string;
    agency: string;
    deliveryTime: string;
    salesCount: bigint;
    price: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lead {
    id: string;
    status: LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    createdAt: bigint;
    revenuePotential: bigint;
    agency: string;
    niche: string;
}
export interface Deal {
    id: string;
    status: DealStatus;
    closeDate?: bigint;
    value: bigint;
    createdAt: bigint;
    agency: string;
    leadId: string;
}
export interface Project {
    id: string;
    files: Array<ExternalBlob>;
    completion: bigint;
    status: string;
    clientId: string;
    agency: string;
    notes: string;
    serviceId: string;
    startDate: bigint;
    milestones: Array<string>;
}
export interface UserProfile {
    revenueGoal: bigint;
    principal: string;
    name: string;
    role: UserRole;
    subscriptionPlan: string;
    agency: string;
    mobileNumber?: string;
    email: string;
    totalRevenue: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DealStatus {
    won = "won",
    lost = "lost",
    open = "open",
    proposalSent = "proposalSent"
}
export enum LeadStatus {
    won = "won",
    cold = "cold",
    lost = "lost",
    proposalSent = "proposalSent",
    contacted = "contacted",
    interested = "interested",
    qualified = "qualified"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLead(request: {
        id: string;
        status: LeadStatus;
        contact: string;
        owner: string;
        city: string;
        name: string;
        revenuePotential: bigint;
        agency: string;
        niche: string;
    }): Promise<void>;
    addOutreach(activity: OutreachActivity): Promise<void>;
    addProject(project: Project): Promise<void>;
    addService(service: Service): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeProject(projectId: string): Promise<void>;
    createClientServiceRequest(serviceId: string, agency: string, details: string | null): Promise<void>;
    getAgencyAnalytics(agency: string): Promise<[Array<Lead>, Array<Deal>, Array<OutreachActivity>, Array<Service>, Array<Project>]>;
    getAllClientServiceRequests(): Promise<Array<ClientServiceRequest>>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllOutreachActivities(): Promise<Array<OutreachActivity>>;
    getAllServices(): Promise<Array<Service>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientServiceRequest(requestId: string): Promise<ClientServiceRequest | null>;
    getClientServiceRequestsByAgency(agency: string): Promise<Array<ClientServiceRequest>>;
    getUserDeals(agency: string): Promise<Array<Deal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importLeads(leadList: Array<Lead>, agency: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(principal: string, name: string, email: string, mobileNumber: string | null, agency: string, role: UserRole, revenueGoal: bigint, subscriptionPlan: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDealStatus(dealId: string, status: DealStatus): Promise<void>;
    updateLeadStatus(leadId: string, status: LeadStatus): Promise<void>;
    updateServiceStatus(serviceId: string, active: boolean): Promise<void>;
}
import type { ClientServiceRequest as _ClientServiceRequest, Deal as _Deal, DealStatus as _DealStatus, ExternalBlob as _ExternalBlob, Lead as _Lead, LeadStatus as _LeadStatus, Project as _Project, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLead(arg0: {
        id: string;
        status: LeadStatus;
        contact: string;
        owner: string;
        city: string;
        name: string;
        revenuePotential: bigint;
        agency: string;
        niche: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOutreach(arg0: OutreachActivity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOutreach(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOutreach(arg0);
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(await to_candid_Project_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(await to_candid_Project_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeProject(arg0);
            return result;
        }
    }
    async createClientServiceRequest(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientServiceRequest(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientServiceRequest(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAgencyAnalytics(arg0: string): Promise<[Array<Lead>, Array<Deal>, Array<OutreachActivity>, Array<Service>, Array<Project>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgencyAnalytics(arg0);
                return [
                    from_candid_vec_n18(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n23(this._uploadFile, this._downloadFile, result[1]),
                    result[2],
                    result[3],
                    from_candid_vec_n29(this._uploadFile, this._downloadFile, result[4])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgencyAnalytics(arg0);
            return [
                from_candid_vec_n18(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n23(this._uploadFile, this._downloadFile, result[1]),
                result[2],
                result[3],
                from_candid_vec_n29(this._uploadFile, this._downloadFile, result[4])
            ];
        }
    }
    async getAllClientServiceRequests(): Promise<Array<ClientServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClientServiceRequests();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClientServiceRequests();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOutreachActivities(): Promise<Array<OutreachActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOutreachActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOutreachActivities();
            return result;
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientServiceRequest(arg0: string): Promise<ClientServiceRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientServiceRequest(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientServiceRequest(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientServiceRequestsByAgency(arg0: string): Promise<Array<ClientServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientServiceRequestsByAgency(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientServiceRequestsByAgency(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDeals(arg0: string): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDeals(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDeals(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async importLeads(arg0: Array<Lead>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importLeads(to_candid_vec_n44(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importLeads(to_candid_vec_n44(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: UserRole, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDealStatus(arg0: string, arg1: DealStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDealStatus(arg0, to_candid_DealStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDealStatus(arg0, to_candid_DealStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeadStatus(arg0: string, arg1: LeadStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateServiceStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ClientServiceRequest_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientServiceRequest): ClientServiceRequest {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DealStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStatus): DealStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LeadStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Project_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Promise<Project> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientServiceRequest]): ClientServiceRequest | null {
    return value.length === 0 ? null : from_candid_ClientServiceRequest_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    createdAt: bigint;
    revenuePotential: bigint;
    agency: string;
    niche: string;
}): {
    id: string;
    status: LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    createdAt: bigint;
    revenuePotential: bigint;
    agency: string;
    niche: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n21(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        owner: value.owner,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        revenuePotential: value.revenuePotential,
        agency: value.agency,
        niche: value.niche
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _DealStatus;
    closeDate: [] | [bigint];
    value: bigint;
    createdAt: bigint;
    agency: string;
    leadId: string;
}): {
    id: string;
    status: DealStatus;
    closeDate?: bigint;
    value: bigint;
    createdAt: bigint;
    agency: string;
    leadId: string;
} {
    return {
        id: value.id,
        status: from_candid_DealStatus_n26(_uploadFile, _downloadFile, value.status),
        closeDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.closeDate)),
        value: value.value,
        createdAt: value.createdAt,
        agency: value.agency,
        leadId: value.leadId
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    files: Array<_ExternalBlob>;
    completion: bigint;
    status: string;
    clientId: string;
    agency: string;
    notes: string;
    serviceId: string;
    startDate: bigint;
    milestones: Array<string>;
}): Promise<{
    id: string;
    files: Array<ExternalBlob>;
    completion: bigint;
    status: string;
    clientId: string;
    agency: string;
    notes: string;
    serviceId: string;
    startDate: bigint;
    milestones: Array<string>;
}> {
    return {
        id: value.id,
        files: await from_candid_vec_n32(_uploadFile, _downloadFile, value.files),
        completion: value.completion,
        status: value.status,
        clientId: value.clientId,
        agency: value.agency,
        notes: value.notes,
        serviceId: value.serviceId,
        startDate: value.startDate,
        milestones: value.milestones
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    principal: string;
    createdAt: bigint;
    agency: string;
    details: [] | [string];
    serviceId: string;
}): {
    id: string;
    principal: string;
    createdAt: bigint;
    agency: string;
    details?: string;
    serviceId: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        createdAt: value.createdAt,
        agency: value.agency,
        details: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.details)),
        serviceId: value.serviceId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revenueGoal: bigint;
    principal: string;
    name: string;
    role: _UserRole;
    subscriptionPlan: string;
    agency: string;
    mobileNumber: [] | [string];
    email: string;
    totalRevenue: bigint;
}): {
    revenueGoal: bigint;
    principal: string;
    name: string;
    role: UserRole;
    subscriptionPlan: string;
    agency: string;
    mobileNumber?: string;
    email: string;
    totalRevenue: bigint;
} {
    return {
        revenueGoal: value.revenueGoal,
        principal: value.principal,
        name: value.name,
        role: from_candid_UserRole_n41(_uploadFile, _downloadFile, value.role),
        subscriptionPlan: value.subscriptionPlan,
        agency: value.agency,
        mobileNumber: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.mobileNumber)),
        email: value.email,
        totalRevenue: value.totalRevenue
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    cold: null;
} | {
    lost: null;
} | {
    proposalSent: null;
} | {
    contacted: null;
} | {
    interested: null;
} | {
    qualified: null;
}): LeadStatus {
    return "won" in value ? LeadStatus.won : "cold" in value ? LeadStatus.cold : "lost" in value ? LeadStatus.lost : "proposalSent" in value ? LeadStatus.proposalSent : "contacted" in value ? LeadStatus.contacted : "interested" in value ? LeadStatus.interested : "qualified" in value ? LeadStatus.qualified : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    lost: null;
} | {
    open: null;
} | {
    proposalSent: null;
}): DealStatus {
    return "won" in value ? DealStatus.won : "lost" in value ? DealStatus.lost : "open" in value ? DealStatus.open : "proposalSent" in value ? DealStatus.proposalSent : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Promise<Array<Project>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Project_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientServiceRequest>): Array<ClientServiceRequest> {
    return value.map((x)=>from_candid_ClientServiceRequest_n35(_uploadFile, _downloadFile, x));
}
function to_candid_DealStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStatus): _DealStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LeadStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Lead_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lead): _Lead {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_Project_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): Promise<_Project> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    files: Array<ExternalBlob>;
    completion: bigint;
    status: string;
    clientId: string;
    agency: string;
    notes: string;
    serviceId: string;
    startDate: bigint;
    milestones: Array<string>;
}): Promise<{
    id: string;
    files: Array<_ExternalBlob>;
    completion: bigint;
    status: string;
    clientId: string;
    agency: string;
    notes: string;
    serviceId: string;
    startDate: bigint;
    milestones: Array<string>;
}> {
    return {
        id: value.id,
        files: await to_candid_vec_n13(_uploadFile, _downloadFile, value.files),
        completion: value.completion,
        status: value.status,
        clientId: value.clientId,
        agency: value.agency,
        notes: value.notes,
        serviceId: value.serviceId,
        startDate: value.startDate,
        milestones: value.milestones
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    createdAt: bigint;
    revenuePotential: bigint;
    agency: string;
    niche: string;
}): {
    id: string;
    status: _LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    createdAt: bigint;
    revenuePotential: bigint;
    agency: string;
    niche: string;
} {
    return {
        id: value.id,
        status: to_candid_LeadStatus_n9(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        owner: value.owner,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        revenuePotential: value.revenuePotential,
        agency: value.agency,
        niche: value.niche
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revenueGoal: bigint;
    principal: string;
    name: string;
    role: UserRole;
    subscriptionPlan: string;
    agency: string;
    mobileNumber?: string;
    email: string;
    totalRevenue: bigint;
}): {
    revenueGoal: bigint;
    principal: string;
    name: string;
    role: _UserRole;
    subscriptionPlan: string;
    agency: string;
    mobileNumber: [] | [string];
    email: string;
    totalRevenue: bigint;
} {
    return {
        revenueGoal: value.revenueGoal,
        principal: value.principal,
        name: value.name,
        role: to_candid_UserRole_n15(_uploadFile, _downloadFile, value.role),
        subscriptionPlan: value.subscriptionPlan,
        agency: value.agency,
        mobileNumber: value.mobileNumber ? candid_some(value.mobileNumber) : candid_none(),
        email: value.email,
        totalRevenue: value.totalRevenue
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    revenuePotential: bigint;
    agency: string;
    niche: string;
}): {
    id: string;
    status: _LeadStatus;
    contact: string;
    owner: string;
    city: string;
    name: string;
    revenuePotential: bigint;
    agency: string;
    niche: string;
} {
    return {
        id: value.id,
        status: to_candid_LeadStatus_n9(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        owner: value.owner,
        city: value.city,
        name: value.name,
        revenuePotential: value.revenuePotential,
        agency: value.agency,
        niche: value.niche
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    won: null;
} | {
    cold: null;
} | {
    lost: null;
} | {
    proposalSent: null;
} | {
    contacted: null;
} | {
    interested: null;
} | {
    qualified: null;
} {
    return value == LeadStatus.won ? {
        won: null
    } : value == LeadStatus.cold ? {
        cold: null
    } : value == LeadStatus.lost ? {
        lost: null
    } : value == LeadStatus.proposalSent ? {
        proposalSent: null
    } : value == LeadStatus.contacted ? {
        contacted: null
    } : value == LeadStatus.interested ? {
        interested: null
    } : value == LeadStatus.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStatus): {
    won: null;
} | {
    lost: null;
} | {
    open: null;
} | {
    proposalSent: null;
} {
    return value == DealStatus.won ? {
        won: null
    } : value == DealStatus.lost ? {
        lost: null
    } : value == DealStatus.open ? {
        open: null
    } : value == DealStatus.proposalSent ? {
        proposalSent: null
    } : value;
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Lead>): Array<_Lead> {
    return value.map((x)=>to_candid_Lead_n45(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
